version: '2'
services:
    tool:
        image: macintoshplus/php:php72
        volumes:
            - ./:/sources
            - /var/www:/var/www
            - /usr/local/bin/composer:/usr/local/bin/composer
        dns:
            - 172.16.1.5
